// ── 서비스별 표준 에러 코드 ─────────────────────────────────
// 형식: DOMAIN_ACTION 또는 DOMAIN_REASON

export const ErrorCode = {
  // ── 공통 ──────────────────────────────────────────────
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  BAD_GATEWAY: 'BAD_GATEWAY',

  // ── Auth ──────────────────────────────────────────────
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INACTIVE_ACCOUNT: 'AUTH_INACTIVE_ACCOUNT',
  AUTH_TOKEN_REQUIRED: 'AUTH_TOKEN_REQUIRED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_NO_ORGANIZATION: 'AUTH_NO_ORGANIZATION',
  AUTH_PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',
  AUTH_SELF_DELETE: 'AUTH_SELF_DELETE',
  AUTH_ROLE_HAS_USERS: 'AUTH_ROLE_HAS_USERS',
  AUTH_ORG_HAS_USERS: 'AUTH_ORG_HAS_USERS',
  AUTH_INVALID_ROLE_NAME: 'AUTH_INVALID_ROLE_NAME',
  AUTH_SLUG_EXISTS: 'AUTH_SLUG_EXISTS',
  AUTH_TEAM_MEMBER_EXISTS: 'AUTH_TEAM_MEMBER_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_ROLE_NOT_FOUND: 'AUTH_ROLE_NOT_FOUND',
  AUTH_ORG_NOT_FOUND: 'AUTH_ORG_NOT_FOUND',
  AUTH_TEAM_NOT_FOUND: 'AUTH_TEAM_NOT_FOUND',
  AUTH_TEAM_MEMBER_NOT_FOUND: 'AUTH_TEAM_MEMBER_NOT_FOUND',
  AUTH_TEAM_HAS_MEMBERS: 'AUTH_TEAM_HAS_MEMBERS',

  // ── Note / ELN ───────────────────────────────────────
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  NOTE_LOCKED: 'NOTE_LOCKED',
  NOTE_SIGNED: 'NOTE_SIGNED',
  NOTE_STATUS_TRANSITION: 'NOTE_STATUS_TRANSITION',
  NOTE_PERMISSION_DENIED: 'NOTE_PERMISSION_DENIED',
  NOTE_NOT_LOCKED: 'NOTE_NOT_LOCKED',
  NOTE_ADMIN_PASSWORD_INVALID: 'NOTE_ADMIN_PASSWORD_INVALID',
  NOTE_DELETE_LOCKED: 'NOTE_DELETE_LOCKED',
  NOTE_LOCK_ROLE_REQUIRED: 'NOTE_LOCK_ROLE_REQUIRED',
  NOTE_IMMUTABLE: 'NOTE_IMMUTABLE',
  REVISION_NOT_FOUND: 'REVISION_NOT_FOUND',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_PERMISSION_DENIED: 'ATTACHMENT_PERMISSION_DENIED',
  LINK_NOT_FOUND: 'LINK_NOT_FOUND',
  LINK_PERMISSION_DENIED: 'LINK_PERMISSION_DENIED',
  LINK_DUPLICATE: 'LINK_DUPLICATE',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',

  // ── Inventory ────────────────────────────────────────
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_BARCODE_EXISTS: 'ITEM_BARCODE_EXISTS',
  ITEM_STOCK_INSUFFICIENT: 'ITEM_STOCK_INSUFFICIENT',
  ITEM_PERMISSION_DENIED: 'ITEM_PERMISSION_DENIED',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_EXISTS: 'CATEGORY_EXISTS',

  // ── File ─────────────────────────────────────────────
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_BLOCKED_MIME: 'FILE_BLOCKED_MIME',
  FILE_NO_FILE: 'FILE_NO_FILE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_METADATA_FAILED: 'FILE_METADATA_FAILED',
  FILE_PERMISSION_DENIED: 'FILE_PERMISSION_DENIED',
  FILE_STORAGE_ERROR: 'FILE_STORAGE_ERROR',

  // ── Signature ────────────────────────────────────────
  SIGNATURE_NOT_FOUND: 'SIGNATURE_NOT_FOUND',
  SIGNATURE_ALREADY_REVOKED: 'SIGNATURE_ALREADY_REVOKED',
  SIGNATURE_PASSWORD_INVALID: 'SIGNATURE_PASSWORD_INVALID',
  SIGNATURE_ADMIN_ONLY: 'SIGNATURE_ADMIN_ONLY',

  // ── Export ───────────────────────────────────────────
  EXPORT_NOT_FOUND: 'EXPORT_NOT_FOUND',
  EXPORT_NOT_COMPLETED: 'EXPORT_NOT_COMPLETED',
  EXPORT_NOT_CANCELLABLE: 'EXPORT_NOT_CANCELLABLE',
  EXPORT_INVALID_TYPE: 'EXPORT_INVALID_TYPE',
  EXPORT_NOT_ALLOWED: 'EXPORT_NOT_ALLOWED',

  // ── Search ───────────────────────────────────────────
  SEARCH_FAVORITE_EXISTS: 'SEARCH_FAVORITE_EXISTS',
  SEARCH_FAVORITE_NOT_FOUND: 'SEARCH_FAVORITE_NOT_FOUND',
  SEARCH_HISTORY_NOT_FOUND: 'SEARCH_HISTORY_NOT_FOUND',
  SEARCH_PERMISSION_DENIED: 'SEARCH_PERMISSION_DENIED',

  // ── Scheduler ─────────────────────────────────────────
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_INACTIVE: 'RESOURCE_INACTIVE',
  RESOURCE_HAS_BOOKINGS: 'RESOURCE_HAS_BOOKINGS',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_PERMISSION_DENIED: 'BOOKING_PERMISSION_DENIED',
  BOOKING_CONFLICT: 'BOOKING_CONFLICT',
  BOOKING_INVALID_DATE: 'BOOKING_INVALID_DATE',
  BOOKING_PAST_DATE: 'BOOKING_PAST_DATE',
  BOOKING_STATUS_TRANSITION: 'BOOKING_STATUS_TRANSITION',
  BOOKING_PENDING_ONLY: 'BOOKING_PENDING_ONLY',

  // ── Notification ─────────────────────────────────────
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // ── Internal ─────────────────────────────────────────
  INTERNAL_AUTH_FAILED: 'INTERNAL_AUTH_FAILED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
