ALTER TABLE "SearchHistory" ADD COLUMN "orgId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Favorite" ADD COLUMN "orgId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SearchKeywordFavorite" ADD COLUMN "orgId" TEXT NOT NULL DEFAULT '';
